version: "3.2"

services:
  hackney-shared-housing-search-test:
    image: hackney-shared-housing-search-test
    build:
      context: .
      dockerfile: Hackney.Shared.HousingSearch.Tests/Dockerfile

      # Mounts the secret at /run/secrets/LBHPACKAGESTOKEN.
      # see https://docs.docker.com/compose/how-tos/use-secrets/#build-secrets
      secrets:
        - LBHPACKAGESTOKEN

secrets:
  LBHPACKAGESTOKEN:
    environment: LBHPACKAGESTOKEN
